{"errorMessage": "'DB_PASSWORD'", "errorType": "KeyError", "stackTrace": ["  File \"/var/lang/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n", "  File \"/var/lang/lib/python3.7/imp.py\", line 171, in load_source\n    module = _load(spec)\n", "  File \"<frozen importlib._bootstrap>\", line 696, in _load\n", "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n", "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n", "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n", "  File \"/var/task/lambda_function.py\", line 3, in <module>\n    import rds_config\n", "  File \"/var/task/rds_config.py\", line 6, in <module>\n    db_password = os.environ['DB_PASSWORD']\n", "  File \"/var/lang/lib/python3.7/os.py\", line 681, in __getitem__\n    raise KeyError(key) from None\n"]}